server:
  port: 8091
  error:
    include-message: always
    include-stacktrace: never

spring:
  h2:
    console:
      enabled: true
  datasource:
   url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
   driverClassName: org.h2.Driver
   #platform: h2
   username: sa
   password:
    
  jpa:
   show-sql: true
   hibernate:
      ddl-auto: update
   database-platform: org.hibernate.dialect.H2Dialect
   defer-datasource-initialization: true
   
logging:
  pattern:
    console: "%d{yy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
    